### ISSUE TITLE
Kindle przestało wspierać .mobi

### ISSUE THREAD

**Issue by Acrivec** [PMKrol/CC-SJP#5]
W związku z czym format ten niezbyt pasuje jako "format kindle" na stronie pobrań słownika. :)

**Comment by PMKrol** [comment]
Mam bardzo starego kindla, więc nie mogę sprawdzić - na moim staruszku nie ma problemu, żeby słownik wgrać (chociaż chyba tylko kablem) i ustawić jako słownik. 
Czy masz dostęp do nowego kindla?
Czy mógłbyś wgrać słownik przez kabel i gdzieś w ustawieniach znaleźć opcję dotyczącą słowników? 
np. wg. tego opisu: https://www.leawo.org/entips/add-dictionary-to-kindle-1372.html

**Comment by JakubKoralewski** [comment]
Potwierdzam, że (Kindle Paperwhite 11gen 5.16.3.1) po wrzuceniu SJP2-202302181714.mobi do documents/dictionaries Kindle wykrywa język polski i słownik jest dostępny. Mimo tego że Send to Kindle wyrzuca błąd jako że mobi nie jest wspierany. Dzięki @PMKrol

**Comment by PMKrol** [comment]
Super! Dziękuję za informację.
